
version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: test1-memcached

    mailhog:
      image: mailhog/mailhog:latest
      container_name: test1-mailhog
      ports:
        - "8091:8025"

    redis:
      image: redis:alpine
      container_name: test1-redis

    mysql:
      image: mysql:5.7
      container_name: test1-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_DATABASE=test
        - MYSQL_USER=test
        - MYSQL_PASSWORD=test
      ports:
        - "8092:3306"

    webserver:
      image: nginx:alpine
      container_name: test1-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: test1-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

